### ISSUE TITLE
[Bug] Some messages bypassing filter

### ISSUE THREAD

**Issue by Nick2bad4u** [jackriccomini/spamfilter-plugin-runelite#10]
Someone has figured out a way to make it, so this plugin doesn't see/filter their message. (No spam score, marking spam does nothing)

[Example](https://gyazo.com/7fb55082f18583b239936a29402769d6)

**Comment by jackriccomini** [comment]
That is interesting. Are other messages processed by the filter (and show a spam score, for example)? It doesn't look to be so widespread that I can reproduce by sitting at the GE on a trade world

**Comment by Nick2bad4u** [comment]
I went to GE and got this screen:

![image](https://github.com/jackriccomini/spamfilter-plugin-runelite/assets/20943337/0f6569d4-55a1-48be-a7fc-92a3c990743d)

**Comment by jackriccomini** [comment]
That's helpful, thanks. I have pushed a fix. The PR to release it to plugin hub is here https://github.com/runelite/plugin-hub/pull/4681. If it happens again then please comment and I will re-open this issue and investigate further

**Comment by Nick2bad4u** [comment]
> That's helpful, thanks. I have pushed a fix. The PR to release it to plugin hub is here [runelite/plugin-hub#4681](https://github.com/runelite/plugin-hub/pull/4681). If it happens again then please comment and I will re-open this issue and investigate further

Is this live already or waiting for approval?

**Comment by jackriccomini** [comment]
> > That's helpful, thanks. I have pushed a fix. The PR to release it to plugin hub is here [runelite/plugin-hub#4681](https://github.com/runelite/plugin-hub/pull/4681). If it happens again then please comment and I will re-open this issue and investigate further
> 
> Is this live already or waiting for approval?

Waiting for approval. After that PR I linked to gets merged (the green badge that says "open" on that page will turn to a purple badge that says "merged") then it will be usable in RL. They've generally been pretty quick to review previous PRs but I'm sure they'll be busy enjoying the new game update so I imagine it might take a couple of days.

**Comment by Nick2bad4u** [comment]
> 

Thanks!
