### ISSUE TITLE
Allow us to mark our own messages as spam/ham

### ISSUE THREAD

**Issue by zeakzz** [jackriccomini/spamfilter-plugin-runelite#3]
i cant click on my own messages that have high spam ratings to mark them as ham which is frustrating

**Comment by jackriccomini** [comment]
Adding a right-click option to your own messages is surprisingly not as easy as it sounds. If you can think of a plugin that already does this then I can take a look at their code and see how they do it. 

If all you want is to not have your own messages be filtered then an easier alternative would be to make your own messages immune from the spam check. I can probably implement that without too much trouble. Does that work for you?

If what you want really is to be able to mark your own message as spam/ham as a roundabout way of training the filter then a good workaround would be manually editing the spam/ham lists at `<RuneLite config folder>/spam-filter/user_bad_corpus.txt` and `<RuneLite config folder>/spam-filter/user_bad_corpus.txt`. Make sure you close RuneLite before doing this.

**Comment by zeakzz** [comment]
the workaround of editing the text file is actually what i have been doing, but yes i would love the option to not filter your own messages, and also maybe the option to not filter friends either
