### ISSUE TITLE
Filter Oveheads option does not block overheads when Chat Filter is enabled

### ISSUE THREAD

**Issue by AustinGarrettR** [jackriccomini/spamfilter-plugin-runelite#5]
Runelite version 1.8.28.

When using the Chat Filter plugin that's installed in base runelite, the filter overheads option in the Spam Filter plugin does not work on messages above the spam threshole.

My chat filter plugin settings are all off or blank, except for collapse game chat. Filter lists are empty, and the issue continues.
Turning off the Chat Filter plugin fixes it, but at the expensive of options like Collapse Game/Player Chat.

**Comment by jackriccomini** [comment]
It's very helpful that you narrowed it down to a conflict with Chat Filter! I've had a quick look and it seems like a race condition where this plugin and Chat Filter both try to process the message simultaneously. It should be a simple enough fix.

**Comment by otygah** [comment]
Hi - is there any update on this? I installed the plugin tonight, and am also experiencing this same issue, and unfortunately the Chat Filter plugin is quite important for me, so disabling it isn't really viable.

**Comment by jackriccomini** [comment]
I've recently moved to a new machine and don't have my dev environment set up yet. I pushed a branch that fixed this issue last year. I'm not sure why I never merged and released that branch. When my environment is set up again I will test the branch and release if it seems okay.

**Comment by jackriccomini** [comment]
I have pushed a fix which is now awaiting review by the plugin hub [here](https://github.com/runelite/plugin-hub/pull/5452)
