### ISSUE TITLE
Removed from plugin hub

### ISSUE THREAD

**Issue by fuzxi** [jackriccomini/spamfilter-plugin-runelite#7]
The plugin is no longer available in the plugin hub. Will it be re-added?

**Comment by jackriccomini** [comment]
Yes. It was disabled due to a crash. The crash has been fixed in this repo. I'll put in a PR to the plugin hub soon to get the plugin re-enabled

**Comment by jackriccomini** [comment]
I've put in a PR here https://github.com/runelite/plugin-hub/pull/3359. If that's merged then it'll be back on the plugin hub

**Comment by jackriccomini** [comment]
PR has merged. Plugin is available again
